spring:
  datasource:
    url: jdbc:postgresql://localhost:5410/bookish
    username: bookish
    password: bookish
    driver-class-name: org.postgresql.Driver

  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB

