spring:
  datasource:
    url: jdbc:mysql://localhost:3310/bookish
    username: bookish
    password: bookish
    driver-class-name: "com.mysql.cj.jdbc.Driver"
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB

